// <auto-generated />
namespace DiplomaOptions.Migrations.CourseOptionMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seed2016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed2016));
        
        string IMigrationMetadata.Id
        {
            get { return "201603251930216_Seed2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
